# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
sudo: required
cache: packages
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'covr::coveralls()'
